### ISSUE TITLE
Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by chinlun** [miki2826/botly#15]
Hi, I just trying the sample code and keep getting the following error when I try to sent message to the bot. Could not figure out what caused it.

SyntaxError: Unexpected token u in JSON at position 0
    at Object.parse (native)
    at _clone (/opt/bitnami/apps/yeepee-messenger-bot/node_modules/botly/lib/Botly.js:569:17)
    at Botly.handleMessage (/opt/bitnami/apps/yeepee-messenger-bot/node_modules/botly/lib/Botly.js:488:18)
    at router.post.ex (/opt/bitnami/apps/yeepee-messenger-bot/node_modules/botly/lib/Botly.js:94:18)
    at Layer.handle [as handle_request] (/opt/bitnami/apps/yeepee-messenger-bot/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/bitnami/apps/yeepee-messenger-bot/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/opt/bitnami/apps/yeepee-messenger-bot/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/bitnami/apps/yeepee-messenger-bot/node_modules/express/lib/router/layer.js:95:5)
    at /opt/bitnami/apps/yeepee-messenger-bot/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/opt/bitnami/apps/yeepee-messenger-bot/node_modules/express/lib/router/index.js:330:12)

**Comment by cAstraea** [comment]
Did you figure it out ? Having the same issue. I think it's a difference between the npm version ?

**Comment by KST123ABC** [comment]
I am having this issue too. Why did you close it and not follow up? @chinlun

**Comment by aellanglet** [comment]
@KST123ABC look here : https://github.com/miki2826/botly/issues/31
Same issue and it seems that my answer worked. 👍  😄 
Hope it will be the same for you ;)

**Comment by cAstraea** [comment]
@KST123ABC Yes @aellanglet is correct! :) Was missing the body parser
