### ISSUE TITLE
Cannot find module grpc

### ISSUE THREAD

**Issue by jsappme** [miki2826/botly#21]
Any idea why I am getting this error on Heroku:

Error: Cannot find module '/app/node_modules/grpc/src/node/extension_binary/grpc_node.node'
2017-03-16T22:45:46.206460+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:469:15)
2017-03-16T22:45:46.206461+00:00 app[web.1]:     at Function.Module._load (module.js:417:25)
2017-03-16T22:45:46.206461+00:00 app[web.1]:     at Module.require (module.js:497:17)
2017-03-16T22:45:46.206462+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-03-16T22:45:46.206463+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
2017-03-16T22:45:46.206463+00:00 app[web.1]:     at Module._compile (module.js:570:32)
2017-03-16T22:45:46.206464+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2017-03-16T22:45:46.206464+00:00 app[web.1]:     at Module.load (module.js:487:32)
2017-03-16T22:45:46.206465+00:00 app[web.1]:     at tryModuleLoad (module.js:446:12)
2017-03-16T22:45:46.206466+00:00 app[web.1]:     at Function.Module._load (module.js:438:3)
2017-03-16T22:45:56.884962+00:00 app[web.1]: module.js:471
2017-03-16T22:45:56.884973+00:00 app[web.1]:     throw err;
2017-03-16T22:45:56.884974+00:00 app[web.1]:     ^

**Comment by miki2826** [comment]
Hi @jsappme 
Don't think it's related to botly.
Found this issue on grpc repo: https://github.com/grpc/grpc/issues/8941

**Comment by jsappme** [comment]
You re right. This issue was related to the npm caching from heroku. I resolved it by disabling caching. Sorry for the confusion. But your answer showed me this repo is well alive. Thanks. Keep up the good job.
