### ISSUE TITLE
Unable to Run Example on heroku

### ISSUE THREAD

**Issue by sushantshekhar20** [miki2826/botly#35]
my code is : 
```
const express = require("express");
const Botly = require("botly");
//const startup = require('./staticstuff');

const pageAccessToken =  'page_access_token_from_facebook'
const verificationToken = 'some_text';
const botly = new Botly({
   accessToken: pageAccessToken, //page access token provided by facebook
    verifyToken: verificationToken, //needed when using express - the verification token you provided when defining the webhook in facebook
    webHookPath: '/', //defaults to "/",
    notificationType: Botly.CONST.REGULAR //already the default (optional),
});

botly.on("message", (senderId, message, data) => {
    let text = `echo: ${data.text}`;

    botly.sendText({
      id: senderId,
      text: text
    });
});


const app = express();
app.use("/webhook", botly.router());
app.listen(process.env.PORT || 3000);
```
 Webhook is successfully verified ! but.....
**WHEN I SEND A MESSAGE ON THE BOT... THIS HAPPENS**
Error from heroku Logs : 

`
2017-08-09T22:37:59.865092+00:00 app[web.1]: SyntaxError: Unexpected token u in JSON at position 0
2017-08-09T22:37:59.865108+00:00 app[web.1]:     at Object.parse (native)
2017-08-09T22:37:59.865109+00:00 app[web.1]:     at _clone (/app/node_modules/botly/lib/Botly.js:600:17)
2017-08-09T22:37:59.865123+00:00 app[web.1]:     at Botly.handleMessage (/app/node_modules/botly/lib/Botly.js:511:18)
2017-08-09T22:37:59.865123+00:00 app[web.1]:     at router.post.ex (/app/node_modules/botly/lib/Botly.js:99:18)
2017-08-09T22:37:59.865129+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2017-08-09T22:37:59.865129+00:00 app[web.1]:     at next (/app/node_modules/express/lib/router/route.js:137:13)
2017-08-09T22:37:59.865130+00:00 app[web.1]:     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
2017-08-09T22:37:59.865130+00:00 app[web.1]:     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2017-08-09T22:37:59.865131+00:00 app[web.1]:     at /app/node_modules/express/lib/router/index.js:281:22
2017-08-09T22:37:59.865131+00:00 app[web.1]:     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
`

**Comment by aellanglet** [comment]
Hi, You have the answer [here](https://github.com/miki2826/botly/issues/31) and [here](https://github.com/miki2826/botly/issues/15).

Juste look at the closed issues... 😠
