### ISSUE TITLE
error: TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by aellanglet** [miki2826/botly#39]
Hello , got this message error : 

`error: TypeError: Cannot read property 'forEach' of undefined
    at Botly.body.entry.forEach.entry (/data/web/nodjs-botnik/web/node_modules/botly/lib/Botly.js:515:24)
    at Array.forEach (<anonymous>)
    at Botly.handleMessage (/data/web/nodjs-botnik/web/node_modules/botly/lib/Botly.js:514:16)
    at router.post (/data/web/nodjs-botnik/web/node_modules/botly/lib/Botly.js:99:18)
    at Layer.handle [as handle_request] (/data/web/nodjs-botnik/web/node_modules/express/lib/router/layer.js:95:5)
    at next (/data/web/nodjs-botnik/web/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/data/web/nodjs-botnik/web/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/data/web/nodjs-botnik/web/node_modules/express/lib/router/layer.js:95:5)
    at /data/web/nodjs-botnik/web/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/data/web/nodjs-botnik/web/node_modules/express/lib/router/index.js:335:12)`

Don't really understand why... This error come anytime i interact with the Chatbot, but this one is working anyway. It don't shut down the server but it's quite annoying to see an error message like this.
Hope someone could have an answer ! 👍

**Comment by aellanglet** [comment]
It's a story about versions, First App was at 2.9 and this one is at 2.10, this add a new entry, that's why and Botly can't handle it yet. :)
