### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by sushantshekhar20** [miki2826/botly#40]
I get this error at every Payload.

```
TypeError: Cannot read property 'forEach' of undefined
    at Botly.body.entry.forEach.entry (/Users/sushantshekhar/Work/BOTUPON/bookingbotdemo/node_modules/botly/lib/Botly.js:515:24)
    at Array.forEach (native)
    at Botly.handleMessage (/Users/sushantshekhar/Work/BOTUPON/bookingbotdemo/node_modules/botly/lib/Botly.js:514:16)
    at router.post (/Users/sushantshekhar/Work/BOTUPON/bookingbotdemo/node_modules/botly/lib/Botly.js:99:18)
    at Layer.handle [as handle_request] (/Users/sushantshekhar/Work/BOTUPON/bookingbotdemo/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/sushantshekhar/Work/BOTUPON/bookingbotdemo/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/sushantshekhar/Work/BOTUPON/bookingbotdemo/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/sushantshekhar/Work/BOTUPON/bookingbotdemo/node_modules/express/lib/router/layer.js:95:5)
    at /Users/sushantshekhar/Work/BOTUPON/bookingbotdemo/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/sushantshekhar/Work/BOTUPON/bookingbotdemo/node_modules/express/lib/router/index.js:335:12)

```

**Comment by aellanglet** [comment]
[had the same yesterday, look here 😄 ](https://github.com/miki2826/botly/issues/39)

**Comment by sushantshekhar20** [comment]
I saw that still could not figure out why am I getting this error.

**Comment by aellanglet** [comment]
Oh weird... Did you turned out "standby", "messaging_handovers", "messaging_policy_enforcement" ? That worked for me !

**Comment by sushantshekhar20** [comment]
That worked for me! Thanks a Lot for the quick replies! 😄
